# configuration for "master" branch
-
  branches:
    only:
      - master
      - /release.*/
  install:
    - choco install gitversion.portable -pre -y
  test: off
  assembly_info:
    patch: false
  nuget:
    disable_publish_on_pr: true
  environment:
    apiKey:
      secure: lrwREUV4nO99AU0A6xVx/MNF0BaJc8A1B8dwEGMLqmYKGqD5E7PJ/IC9RHcle6pk
  before_build:
    - ps: gitversion /l console /output buildserver
    - nuget setapikey %apiKey% -Verbosity quiet
  build_script:
    - build.bat /t:CoverageUpload;Deploy /v:m
# all other branches
-
  install:
    - choco install gitversion.portable -pre -y
  test: off
  assembly_info:
    patch: false
  nuget:
    disable_publish_on_pr: true
  before_build:
    - ps: gitversion /l console /output buildserver
  build_script:
    - build.bat /t:CoverageUpload;Package /v:m
